import { JobCategory, Job, Language } from "./types";

export const LANGUAGES: Language[] = [
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "or", name: "Odia", nativeName: "ଓಡಿଆ" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "ks", name: "Kashmiri", nativeName: "कॉशুর" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
];

export const STATES_AND_CITIES: Record<string, string[]> = {
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  Karnataka: ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum"],
  Delhi: [
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "East Delhi",
    "West Delhi",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
  ],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
};

export const ADMIN_WHITELIST = [
  "9876543210",
  "9123456789",
  "9999999999",
  "8888888888",
];

export const CATEGORIES = [
  {
    id: JobCategory.HOTEL,
    label: "Hotel / Restaurant",
    icon: "fa-utensils",
    color: "bg-orange-500",
  },
  {
    id: JobCategory.SHOP,
    label: "Shop / Store",
    icon: "fa-shop",
    color: "bg-blue-500",
  },
  {
    id: JobCategory.GARAGE,
    label: "Garage / Mechanic",
    icon: "fa-screwdriver-wrench",
    color: "bg-slate-700",
  },
  {
    id: JobCategory.DELIVERY,
    label: "Delivery",
    icon: "fa-motorcycle",
    color: "bg-yellow-500",
  },
  {
    id: JobCategory.CONSTRUCTION,
    label: "Construction",
    icon: "fa-helmet-safety",
    color: "bg-amber-600",
  },
  {
    id: JobCategory.HOUSE_HELP,
    label: "House Help",
    icon: "fa-broom",
    color: "bg-pink-500",
  },
  {
    id: JobCategory.SECURITY,
    label: "Security Guard",
    icon: "fa-shield-halved",
    color: "bg-emerald-600",
  },
  {
    id: JobCategory.OTHER,
    label: "Others",
    icon: "fa-ellipsis",
    color: "bg-gray-500",
  },
];

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Assistant Cook",
    jobRole: "Assistant Cook",
    industry: "Hotel / Restaurant",
    category: JobCategory.HOTEL,
    employerId: "emp1",
    employerName: "Sharma Dhaba",
    description:
      "Looking for a helper in the kitchen. Must know basic veg cooking. Lunch provided.",
    contact: { callNumber: "9988776655", whatsappNumber: "9988776655" },
    shopPhoto: {
      url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=400",
      uploadedAt: daysAgo(0),
    },
    location: {
      lat: 19.076,
      lng: 72.8777,
      address: "Andheri East, Mumbai",
      state: "Maharashtra",
      city: "Mumbai",
    },
    salaryAmount: "600",
    salaryType: "DAY",
    isVerified: true,
    isPromoted: true,
    status: "APPROVED",
    isLive: true,
    callCount: 12,
    whatsappCount: 8,
    createdAt: daysAgo(0),
    expiryDays: 15,
    experienceLevel: "Entry Level",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "2",
    title: "Security Guard",
    jobRole: "Security Guard",
    industry: "Office / Services",
    category: JobCategory.SECURITY,
    employerId: "emp2",
    employerName: "Royal Heights Society",
    description:
      "12-hour shift for residential society. Uniform provided. Previous experience preferred.",
    contact: { callNumber: "9876543210", whatsappNumber: "9876543210" },
    shopPhoto: null,
    location: {
      lat: 19.1136,
      lng: 72.8697,
      address: "Marol, Mumbai",
      state: "Maharashtra",
      city: "Mumbai",
    },
    salaryAmount: "15000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 5,
    whatsappCount: 2,
    createdAt: daysAgo(1),
    expiryDays: 7,
    experienceLevel: "1-2 Years",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "3",
    title: "Home Cleaner",
    jobRole: "Home Cleaner",
    industry: "Other",
    category: JobCategory.HOUSE_HELP,
    employerId: "emp3",
    employerName: "Malhotra Family",
    description:
      "Part-time cleaning work for 2 BHK apartment. Morning hours only.",
    contact: { callNumber: "9123456780", whatsappNumber: "9123456780" },
    shopPhoto: null,
    location: {
      lat: 19.033,
      lng: 72.8777,
      address: "Sion, Mumbai",
      state: "Maharashtra",
      city: "Mumbai",
    },
    salaryAmount: "8000",
    salaryType: "MONTH",
    isVerified: false,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 2,
    whatsappCount: 1,
    createdAt: daysAgo(2),
    expiryDays: 10,
    experienceLevel: "Fresher",
    employmentType: "Part Time",
    workMode: "On-site",
  },
  {
    id: "4",
    title: "Two Wheeler Mechanic",
    jobRole: "Bike Mechanic",
    industry: "Automobile / Garage",
    category: JobCategory.GARAGE,
    employerId: "emp4",
    employerName: "FastFix Motors",
    description:
      "Experienced bike mechanic needed for a busy garage in Bangalore. Specialization in Royal Enfield is a plus.",
    contact: { callNumber: "9845012345", whatsappNumber: "9845012345" },
    shopPhoto: {
      url: "https://images.unsplash.com/photo-1590674899484-d33d5ef7c78a?auto=format&fit=crop&q=80&w=400",
      uploadedAt: daysAgo(1),
    },
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: "Koramangala, Bangalore",
      state: "Karnataka",
      city: "Bangalore",
    },
    salaryAmount: "18000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 8,
    whatsappCount: 4,
    createdAt: daysAgo(1),
    expiryDays: 20,
    experienceLevel: "Senior",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "5",
    title: "Delivery Rider",
    jobRole: "Zomato/Swiggy Delivery",
    industry: "Logistics",
    category: JobCategory.DELIVERY,
    employerId: "emp5",
    employerName: "Blue Dart Hub",
    description:
      "Delivery of food and parcels in local area. Must have own bike and valid driving license.",
    contact: { callNumber: "9765432109", whatsappNumber: "9765432109" },
    shopPhoto: {
      url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=400",
      uploadedAt: daysAgo(0),
    },
    location: {
      lat: 28.6139,
      lng: 77.209,
      address: "Connaught Place, Delhi",
      state: "Delhi",
      city: "New Delhi",
    },
    salaryAmount: "12000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: true,
    status: "APPROVED",
    isLive: true,
    callCount: 20,
    whatsappCount: 15,
    createdAt: daysAgo(0),
    expiryDays: 30,
    experienceLevel: "Fresher",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "6",
    title: "Construction Labor",
    jobRole: "General Laborer",
    industry: "Construction",
    category: JobCategory.CONSTRUCTION,
    employerId: "emp6",
    employerName: "Buildwell Infra",
    description:
      "Helper needed for site work. Daily payment provided. Hardworking individuals preferred.",
    contact: { callNumber: "9822011223", whatsappNumber: "9822011223" },
    shopPhoto: null,
    location: {
      lat: 18.5204,
      lng: 73.8567,
      address: "Kothrud, Pune",
      state: "Maharashtra",
      city: "Pune",
    },
    salaryAmount: "500",
    salaryType: "DAY",
    isVerified: false,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 3,
    whatsappCount: 1,
    createdAt: daysAgo(1),
    expiryDays: 10,
    experienceLevel: "No Experience",
    employmentType: "Part Time",
    workMode: "On-site",
  },
  {
    id: "7",
    title: "Retail Sales Executive",
    jobRole: "Store Sales Assistant",
    industry: "Retail / Shop",
    category: JobCategory.SHOP,
    employerId: "emp7",
    employerName: "Fashion Hub",
    description:
      "Looking for friendly staff for clothing store. Basic English/Hindi communication required.",
    contact: { callNumber: "9988007766", whatsappNumber: "9988007766" },
    shopPhoto: {
      url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=400",
      uploadedAt: daysAgo(1),
    },
    location: {
      lat: 22.5726,
      lng: 88.3639,
      address: "Park Street, Kolkata",
      state: "West Bengal",
      city: "Kolkata",
    },
    salaryAmount: "14000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 15,
    whatsappCount: 5,
    createdAt: daysAgo(0),
    expiryDays: 15,
    experienceLevel: "Entry Level",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "8",
    title: "Office Boy / Peon",
    jobRole: "Office Helper",
    industry: "Office / Services",
    category: JobCategory.OTHER,
    employerId: "emp8",
    employerName: "Vertex Solutions",
    description:
      "Filing, serving tea/coffee, and small errands. Should know local roads.",
    contact: { callNumber: "9111222333", whatsappNumber: "9111222333" },
    shopPhoto: null,
    location: {
      lat: 23.0225,
      lng: 72.5714,
      address: "Satellite, Ahmedabad",
      state: "Gujarat",
      city: "Ahmedabad",
    },
    salaryAmount: "11000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 7,
    whatsappCount: 3,
    createdAt: daysAgo(2),
    expiryDays: 20,
    experienceLevel: "Entry Level",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "9",
    title: "Truck Driver",
    jobRole: "Heavy Vehicle Driver",
    industry: "Logistics",
    category: JobCategory.DELIVERY,
    employerId: "emp9",
    employerName: "Patel Transports",
    description:
      "Driving 10-wheeler trucks interstate. Valid HMV license is mandatory.",
    contact: { callNumber: "9444055566", whatsappNumber: "9444055566" },
    shopPhoto: null,
    location: {
      lat: 13.0827,
      lng: 80.2707,
      address: "Koyambedu, Chennai",
      state: "Tamil Nadu",
      city: "Chennai",
    },
    salaryAmount: "25000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: true,
    status: "APPROVED",
    isLive: true,
    callCount: 2,
    whatsappCount: 0,
    createdAt: daysAgo(3),
    expiryDays: 30,
    experienceLevel: "3+ Years",
    employmentType: "Full Time",
    workMode: "On-site",
  },
  {
    id: "10",
    title: "Laundry Helper",
    jobRole: "Ironing/Washing Staff",
    industry: "Other",
    category: JobCategory.HOUSE_HELP,
    employerId: "emp10",
    employerName: "Bright Cleaners",
    description:
      "Ironing clothes and washing assistance. Free stay provided for one person.",
    contact: { callNumber: "9811001122", whatsappNumber: "9811001122" },
    shopPhoto: {
      url: "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&q=80&w=400",
      uploadedAt: daysAgo(0),
    },
    location: {
      lat: 26.8467,
      lng: 80.9462,
      address: "Gomti Nagar, Lucknow",
      state: "Uttar Pradesh",
      city: "Lucknow",
    },
    salaryAmount: "9000",
    salaryType: "MONTH",
    isVerified: false,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 4,
    whatsappCount: 2,
    createdAt: daysAgo(0),
    expiryDays: 10,
    experienceLevel: "Fresher",
    employmentType: "Full Time",
    workMode: "On-site",
  },
];
