import { JobCategory, Job, Language } from "./types";

export const LANGUAGES: Language[] = [
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "or", name: "Odia", nativeName: "ଓಡಿଆ" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "ks", name: "Kashmiri", nativeName: "कॉशুর" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
];

export const STATES_AND_CITIES: Record<string, string[]> = {
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  Karnataka: ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum"],
  Delhi: [
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "East Delhi",
    "West Delhi",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
  ],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
};

export const ADMIN_WHITELIST = [
  "9876543210",
  "9123456789",
  "9999999999",
  "8888888888",
];

export const CATEGORIES = [
  {
    id: JobCategory.DRIVER,
    label: "Driver",
    icon: "fa-car",
    color: "bg-indigo-500",
  },
  {
    id: JobCategory.DELIVERY_LOGISTICS,
    label: "Delivery & Logistics",
    icon: "fa-motorcycle",
    color: "bg-yellow-500",
  },
  {
    id: JobCategory.HOUSEHOLD,
    label: "Household",
    icon: "fa-broom",
    color: "bg-pink-500",
  },
  {
    id: JobCategory.CONSTRUCTION,
    label: "Construction",
    icon: "fa-helmet-safety",
    color: "bg-amber-600",
  },
  {
    id: JobCategory.RETAIL,
    label: "Retail",
    icon: "fa-store",
    color: "bg-blue-500",
  },
  {
    id: JobCategory.FACTORY_MANUFACTURING,
    label: "Factory & Manufacturing",
    icon: "fa-industry",
    color: "bg-gray-700",
  },
  {
    id: JobCategory.SECURITY,
    label: "Security",
    icon: "fa-shield-halved",
    color: "bg-emerald-600",
  },
  {
    id: JobCategory.HOSPITALITY,
    label: "Hospitality",
    icon: "fa-utensils",
    color: "bg-orange-500",
  },
  {
    id: JobCategory.OFFICE_SERVICES,
    label: "Office & Services",
    icon: "fa-briefcase",
    color: "bg-slate-600",
  },
  {
    id: JobCategory.AUTOMOBILE,
    label: "Automobile",
    icon: "fa-screwdriver-wrench",
    color: "bg-slate-800",
  },
  {
    id: JobCategory.HEALTHCARE_SUPPORT,
    label: "Healthcare Support",
    icon: "fa-heart-pulse",
    color: "bg-red-500",
  },
  {
    id: JobCategory.AGRICULTURE,
    label: "Agriculture",
    icon: "fa-seedling",
    color: "bg-green-600",
  },
  {
    id: JobCategory.GIG_ON_DEMAND,
    label: "Gig & On-demand",
    icon: "fa-bolt",
    color: "bg-purple-600",
  },
];

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const MOCK_JOBS: Job[] = [
  {
    id: "drv1",
    title: "Cab Driver",
    jobRole: "Taxi Driver",
    industry: "Driver",
    category: JobCategory.DRIVER,
    employerId: "emp_drv",
    employerName: "City Cabs",
    description: "Looking for experienced cab drivers with valid license.",
    contact: { callNumber: "9000000001", whatsappNumber: "9000000001" },
    shopPhoto: null,
    location: {
      lat: 28.6139,
      lng: 77.209,
      address: "Delhi",
      state: "Delhi",
      city: "Delhi",
    },
    salaryAmount: "22000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 0,
    whatsappCount: 0,
    createdAt: daysAgo(1),
    expiryDays: 30,
    experienceLevel: "1-2 Years",
    employmentType: "Full Time",
    workMode: "On-site",
  },

  {
    id: "del1",
    title: "Food Delivery Partner",
    jobRole: "Delivery Rider",
    industry: "Delivery & Logistics",
    category: JobCategory.DELIVERY_LOGISTICS,
    employerId: "emp_del",
    employerName: "Swiggy",
    description: "Deliver food orders using your own bike.",
    contact: { callNumber: "9000000002", whatsappNumber: "9000000002" },
    shopPhoto: null,
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: "Bangalore",
      state: "Karnataka",
      city: "Bangalore",
    },
    salaryAmount: "18000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: true,
    status: "APPROVED",
    isLive: true,
    callCount: 0,
    whatsappCount: 0,
    createdAt: daysAgo(0),
    expiryDays: 30,
    experienceLevel: "Fresher",
    employmentType: "Full Time",
    workMode: "On-site",
  },

  {
    id: "ret1",
    title: "Store Sales Boy",
    jobRole: "Retail Assistant",
    industry: "Retail",
    category: JobCategory.RETAIL,
    employerId: "emp_ret",
    employerName: "Reliance Trends",
    description: "Assist customers and manage billing.",
    contact: { callNumber: "9000000003", whatsappNumber: "9000000003" },
    shopPhoto: null,
    location: {
      lat: 19.076,
      lng: 72.8777,
      address: "Mumbai",
      state: "Maharashtra",
      city: "Mumbai",
    },
    salaryAmount: "15000",
    salaryType: "MONTH",
    isVerified: true,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 0,
    whatsappCount: 0,
    createdAt: daysAgo(2),
    expiryDays: 20,
    experienceLevel: "Entry Level",
    employmentType: "Full Time",
    workMode: "On-site",
  },

  {
    id: "agri1",
    title: "Farm Worker",
    jobRole: "Agriculture Helper",
    industry: "Agriculture",
    category: JobCategory.AGRICULTURE,
    employerId: "emp_agri",
    employerName: "Green Farms",
    description: "Farm labor work including harvesting and watering.",
    contact: { callNumber: "9000000004", whatsappNumber: "9000000004" },
    shopPhoto: null,
    location: {
      lat: 26.9124,
      lng: 75.7873,
      address: "Jaipur",
      state: "Rajasthan",
      city: "Jaipur",
    },
    salaryAmount: "500",
    salaryType: "DAY",
    isVerified: false,
    isPromoted: false,
    status: "APPROVED",
    isLive: true,
    callCount: 0,
    whatsappCount: 0,
    createdAt: daysAgo(3),
    expiryDays: 10,
    experienceLevel: "No Experience",
    employmentType: "Part Time",
    workMode: "On-site",
  },

  {
    id: "gig1",
    title: "Event Helper",
    jobRole: "Gig Worker",
    industry: "Gig",
    category: JobCategory.GIG_ON_DEMAND,
    employerId: "emp_gig",
    employerName: "EventPro",
    description: "One-day event setup and support work.",
    contact: { callNumber: "9000000005", whatsappNumber: "9000000005" },
    shopPhoto: null,
    location: {
      lat: 17.385,
      lng: 78.4867,
      address: "Hyderabad",
      state: "Telangana",
      city: "Hyderabad",
    },
    salaryAmount: "1000",
    salaryType: "DAY",
    isVerified: false,
    isPromoted: true,
    status: "APPROVED",
    isLive: true,
    callCount: 0,
    whatsappCount: 0,
    createdAt: daysAgo(0),
    expiryDays: 5,
    experienceLevel: "Fresher",
    employmentType: "Temporary",
    workMode: "On-site",
  },
];
